default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: incom_development

test:
  <<: *default
  database: incom_test

staging:
  <<: *default
  database: incom_staging

production:
  <<: *default
  database: incom_production
